### ISSUE TITLE
Can't install on Android 

### ISSUE THREAD

**Issue by MasterZebulin** [scoliono/archiveripper#11]
I don't know how to install this on Android because "I'm dumb". There's no button to install the script to the browser.

**Comment by scoliono** [comment]
Hi, this is intended to run as a Python program, not a userscript or browser extension.

**Comment by MasterZebulin** [comment]
What the heck is Python?

Sent from AT&T Yahoo Mail on Android 
 
  On Sun, Jun 30, 2024 at 10:40 AM, ***@***.***> wrote:   


Hi, this is intended to run as a Python program, not a userscript or browser extension.
