### ISSUE TITLE
ERROR: UNAVAILABLE assertion error

### ISSUE THREAD

**Issue by seasaltseasalt** [scoliono/archiveripper#4]
Thankyou v much, for creating this script.

Installed on catalina 10.15.6, python3.8
Installed this scripts, dev branch as suggested in other issue.

I have not been able to get a title successful yet. Apologises if I am doing something obvious and silly.

How do I check I have it installed correctly?
or that I am logged in correctly? (So I know it is an issue with the title versus me)

ERROR Message: UNAVAILABLE: 

From Terminal

% python3 ripper.py
Look for the book's identifier (the part of the url immediately after "https://archive.org/details/").
Enter it here: chopmarks1987rose
Enter your archive.org email: xxx
Enter your archive.org password: xxx
ERROR:root:error with action browse_book: Unexpected error.
Please email this link to openlibrary@archive.org with the subject: Unexpected error. Thank you. 
Message:UNAVAILABLE
Traceback (most recent call last):
  File "ripper.py", line 101, in <module>
    main()
  File "ripper.py", line 43, in main
    client.schedule_loan_book(id)
  File "/Users/xxx/DP/MAC/api.py", line 79, in schedule_loan_book
    self.borrow_book(book_id)
  File "/Users/xxx/DP/MAC/api.py", line 35, in borrow_book
    raise AssertionError
AssertionError

**Comment by seasaltseasalt** [comment]
Same error received if title is DAISY (tested primeronregressi0000camp)

**Comment by notevenaperson** [comment]
This script works by scraping archive.org's web-reader, available after a book is borrowed. If the book you want can't be borrowed on archive.org the script can't do anything, which was the case in the 2 books that you tried to download.

**Comment by seasaltseasalt** [comment]
thankyou for lmk
